name: "🐞 Bug Report"
description: "Report a bug in the project."
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees:
  - maintainer-username
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill in the details below to help us resolve the issue.
  - type: input
    id: os
    attributes:
      label: "Operating System"
      description: "What OS are you using?"
      placeholder: "Example: Windows 10, macOS Ventura"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "Describe the issue in detail."
      placeholder: "Explain what happened and what you expected to happen."
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to reproduce the issue."
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll to '...'
        4. See the error
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: "Screenshots or Logs"
      description: "Attach relevant screenshots or logs."
