name: "✨ Feature Request"
description: "Suggest a new feature or improvement."
title: "[Feature]: "
labels: ["enhancement", "discussion"]
assignees:
  - maintainer-username
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide the details below.
  - type: input
    id: motivation
    attributes:
      label: "Motivation"
      description: "Why is this feature needed?"
      placeholder: "Explain the problem it solves or the need it fulfills."
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Feature Description"
      description: "Describe how this feature should work."
      placeholder: "Provide details about how it should be implemented."
    validations:
      required: true
  - type: input
    id: alternatives
    attributes:
      label: "Alternative Solutions"
      description: "Have you considered other ways to implement this?"
      placeholder: "Describe any alternative solutions you've thought about."
