name: "❓ Question"
description: "Ask a question about the project."
title: "[Question]: "
labels: ["question"]
assignees:
  - maintainer-username
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in the project! Please write your question below.
  - type: textarea
    id: question
    attributes:
      label: "Your Question"
      description: "Describe your question clearly and concisely."
      placeholder: "Provide details about your doubt or concern."
    validations:
      required: true
